services:
  frontend:
    build: 
      context : ./frontend
      args:
        DOMAIN_NAME : ${DOMAIN_NAME}
    ports: 
      - 8080:80
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8090:8090