services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    ports:
      - "8080:80"
    volumes:
      - "./frontend:/app"
    networks:
      tea-dev:


networks:
  tea-dev: