services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
  reverse-proxy-local:
    build:
      context: ./reverse-proxy-local
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8080:8080
